#!/bin/sh

#aspell settings
ln -sf "`pwd`/aspell/.aspell."* "$HOME/"

#TeX settings
ln -sf "`pwd`/YaTeX/.yatexrc" "$HOME/"
ln -sf "`pwd`/latexmk/.latexmkrc" "$HOME/"
if ! [ -e "$HOME/texmf" ]
then
	mkdir "$HOME/texmf" 
fi

#bash settings
ln -sf "`pwd`/bash/.bash"* "$HOME/"
if ! [ -e "$HOME/bin" ] 
then
	mkdir "$HOME/bin"
fi
ln -sf "`pwd`/bash/addpath" "$HOME/bin/"

#emacs settings
if ! [ -d "`pwd`/.emacs.d" ]
then
	git clone git@github.com:YukihiroMasuoka/.emacs.d.git
fi
ln -sf "`pwd`/.emacs.d" "$HOME/"

#nvim settings
if ! [ -e "$HOME/.config" ] 
then
	mkdir "$HOME/.config"
fi

if ! [ -e "$HOME/.config/nvim" ] 
then
	ln -sf "`pwd`/nvim" "$HOME/.config/"
fi

if ! [ -e "$HOME/.cache/dein" ]
then
	curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "$HOME/deininstaller.sh"
	sh $HOME/deininstaller.sh "$HOME/.cache/dein"
fi

#tmux
ln -sf "`pwd`/tmux/.tmux.conf" "$HOME/"
